project:
  type: "website"
  title: "RNA-Editing"
  output-dir: docs
  render:
    - "index.qmd"
    - "analysis/202*.qmd"
    - "makefigs/*.qmd"
    - "!code/"
    - "!data/"
    - "!output"

website:
  title: "RNA-Editing"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - about.qmd
    # logo: assets/logo.png
    background: "dark"
    search: true
format:
  html:
    theme: yeti
    css: styles.css
